// We will need to export function here?
import { GoogleSpreadsheet } from 'google-spreadsheet';
import { gsheet } from '../config/config';

const doc = new GoogleSpreadsheet('1wgf7tjvwlQtGEXtJrcNEgBY3CC9J_kOioU4U3EkVlO8');

export const mainFun = async (user, walletaddress) => {
    await doc.useServiceAccountAuth({
        // env var values are copied from service account credentials generated by google
        // see "Authentication" section in docs for more info
        client_email: gsheet.gemail,
        private_key: gsheet.key,
    });
    await doc.loadInfo(); // loads document properties and worksheets

    const sheet = doc.sheetsByIndex[0]; // or use doc.sheetsById[id] or doc.sheetsByTitle[title]
    const rows = await sheet.getRows();
    const found = rows.filter(row => row.name == user || row.wallet == walletaddress);

    if (found.length == 0) {
        await sheet.addRow({ name: user, wallet: walletaddress });
        return true;
    }
    return false;
};
